"""
QShield Enterprise
==================

AI Recommendation Model

Stores AI-generated remediation recommendations for findings,
compliance gaps, and security posture improvements.

Recommendations are generated by the QShield Intelligence Engine
and remain traceable to the originating scan and (optionally)
an individual finding.
"""

from __future__ import annotations

import enum
import uuid

from sqlalchemy import (
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)

from sqlalchemy.orm import (
    Mapped,
    mapped_column,
    relationship,
)

from app.database.base import Base
from app.database.mixins import (
    TimestampMixin,
    UUIDMixin,
)
from app.database.types import GUID


# ============================================================
# ENUMS
# ============================================================


class RecommendationPriority(str, enum.Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class RecommendationStatus(str, enum.Enum):
    GENERATED = "Generated"
    REVIEWED = "Reviewed"
    ACCEPTED = "Accepted"
    IMPLEMENTED = "Implemented"
    REJECTED = "Rejected"


# ============================================================
# MODEL
# ============================================================


class AIRecommendation(
    UUIDMixin,
    TimestampMixin,
    Base,
):
    """
    AI-generated remediation recommendation.
    """

    __tablename__ = "ai_recommendations"

    __table_args__ = (
        Index("idx_ai_scan", "scan_id"),
        Index("idx_ai_finding", "finding_id"),
        Index("idx_ai_priority", "priority"),
    )

    # ============================================================
    # Relationships
    # ============================================================

    scan_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey(
            "scans.id",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    finding_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(),
        ForeignKey(
            "findings.id",
            ondelete="SET NULL",
        ),
    )

    # ============================================================
    # Recommendation
    # ============================================================

    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    recommendation: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    rationale: Mapped[str | None] = mapped_column(
        Text,
    )

    implementation_guidance: Mapped[str | None] = mapped_column(
        Text,
    )

    references: Mapped[str | None] = mapped_column(
        Text,
    )

    # ============================================================
    # Assessment
    # ============================================================

    priority: Mapped[RecommendationPriority] = mapped_column(
        Enum(RecommendationPriority),
        nullable=False,
    )

    confidence: Mapped[float] = mapped_column(
        Float,
        default=0.0,
    )

    estimated_effort_hours: Mapped[int | None] = mapped_column(
        Integer,
    )

    business_impact: Mapped[str | None] = mapped_column(
        String(255),
    )

    status: Mapped[RecommendationStatus] = mapped_column(
        Enum(RecommendationStatus),
        default=RecommendationStatus.GENERATED,
        nullable=False,
    )

    # ============================================================
    # Relationships
    # ============================================================

    scan = relationship(
        "Scan",
        back_populates="ai_recommendations",
    )

    finding = relationship(
        "Finding",
        back_populates="ai_recommendations",
    )
        # ============================================================
    # Helper Properties
    # ============================================================

    @property
    def confidence_percentage(self) -> float:
        """
        Return the confidence score as a percentage.

        The stored confidence is expected to be in the range [0.0, 1.0].
        Values outside this range are clamped.
        """

        confidence = max(0.0, min(self.confidence, 1.0))
        return round(confidence * 100.0, 2)

    @property
    def is_high_priority(self) -> bool:
        """
        Returns True for High and Critical recommendations.
        """

        return self.priority in (
            RecommendationPriority.HIGH,
            RecommendationPriority.CRITICAL,
        )

    @property
    def is_actionable(self) -> bool:
        """
        Returns True when the recommendation has not yet been fully
        implemented or rejected.
        """

        return self.status not in (
            RecommendationStatus.IMPLEMENTED,
            RecommendationStatus.REJECTED,
        )

    @property
    def has_guidance(self) -> bool:
        """
        Returns True when implementation guidance exists.
        """

        return bool(
            self.implementation_guidance
            and self.implementation_guidance.strip()
        )

    # ============================================================
    # Serialization
    # ============================================================

    def to_dict(self) -> dict:
        return {
            "id": str(self.id),
            "scan_id": str(self.scan_id),
            "finding_id": (
                str(self.finding_id)
                if self.finding_id
                else None
            ),
            "title": self.title,
            "recommendation": self.recommendation,
            "rationale": self.rationale,
            "implementation_guidance": self.implementation_guidance,
            "references": self.references,
            "priority": self.priority.value,
            "confidence": self.confidence,
            "confidence_percentage": self.confidence_percentage,
            "estimated_effort_hours": self.estimated_effort_hours,
            "business_impact": self.business_impact,
            "status": self.status.value,
            "is_high_priority": self.is_high_priority,
            "is_actionable": self.is_actionable,
            "has_guidance": self.has_guidance,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }

    # ============================================================
    # Representation
    # ============================================================

    def __repr__(self) -> str:
        return (
            "<AIRecommendation("
            f"id={self.id}, "
            f"title='{self.title}', "
            f"priority='{self.priority.value}', "
            f"status='{self.status.value}'"
            ")>"
        )